import type { Category, Product } from "@/lib/types";

// Fallback catalog used only when Supabase env vars aren't set (e.g. a fresh clone). Mirrors supabase/seed.sql.
export const categories: Category[] = [
  { slug: "engine-oils", name: "Engine Oils" },
  { slug: "brake-shoes", name: "Brake Shoes & Pads" },
  { slug: "filters", name: "Filters" },
  { slug: "batteries", name: "Batteries" },
  { slug: "spark-plugs", name: "Spark Plugs" },
  { slug: "chains", name: "Chains & Sprockets" },
];

export const products: Product[] = [
  {
    slug: "castrol-activ-4t-10w30-1l",
    name: "Activ 4T 10W-30",
    brand: "Castrol",
    category: "engine-oils",
    price: 480,
    size: "1 L",
    description: "Semi-synthetic 4-stroke engine oil for everyday motorcycle use.",
    specs: [
      { label: "Grade", value: "10W-30" },
      { label: "Type", value: "Semi-synthetic" },
      { label: "Pack", value: "1 L" },
    ],
    compatibleWith: ["Splendor", "Passion", "Pulsar 150", "Activa"],
    inStock: true,
  },
  {
    slug: "servo-4t-plus-20w40-900ml",
    name: "4T Plus 20W-40",
    brand: "Servo",
    category: "engine-oils",
    price: 360,
    size: "900 ml",
    description: "Mineral 4-stroke engine oil, good value for older bikes.",
    specs: [
      { label: "Grade", value: "20W-40" },
      { label: "Type", value: "Mineral" },
      { label: "Pack", value: "900 ml" },
    ],
    compatibleWith: ["Splendor", "CD 100", "Platina"],
    inStock: true,
  },
  {
    slug: "mrf-brake-shoe-set-rear",
    name: "Rear Brake Shoe Set",
    brand: "MRF",
    category: "brake-shoes",
    price: 220,
    size: "Set of 2",
    description: "Long-life rear drum brake shoes with strong, quiet stopping power.",
    specs: [
      { label: "Position", value: "Rear" },
      { label: "Type", value: "Drum" },
      { label: "Pack", value: "Set of 2" },
    ],
    compatibleWith: ["Splendor", "Passion", "Glamour"],
    inStock: true,
  },
  {
    slug: "bosch-front-disc-pad-set",
    name: "Front Disc Brake Pad Set",
    brand: "Bosch",
    category: "brake-shoes",
    price: 550,
    size: "Set of 2",
    description: "Low-dust front disc pads for reliable braking in all weather.",
    specs: [
      { label: "Position", value: "Front" },
      { label: "Type", value: "Disc" },
      { label: "Pack", value: "Set of 2" },
    ],
    compatibleWith: ["Pulsar 150", "Apache RTR", "Unicorn"],
    inStock: true,
  },
  {
    slug: "hiflofiltro-oil-filter",
    name: "Oil Filter",
    brand: "Hiflofiltro",
    category: "filters",
    price: 180,
    description: "High-quality oil filter to keep your engine clean.",
    specs: [
      { label: "Type", value: "Oil filter" },
      { label: "Pack", value: "1 pc" },
    ],
    compatibleWith: ["Pulsar 150", "Pulsar 180", "Avenger"],
    inStock: true,
  },
  {
    slug: "exide-12v-5ah-battery",
    name: "12V 5Ah Battery",
    brand: "Exide",
    category: "batteries",
    price: 1150,
    description: "Maintenance-free two-wheeler battery.",
    specs: [
      { label: "Voltage", value: "12 V" },
      { label: "Capacity", value: "5 Ah" },
    ],
    compatibleWith: ["Activa", "Jupiter", "Splendor"],
    inStock: false,
  },
  {
    slug: "ngk-spark-plug-cr7hsa",
    name: "Spark Plug CR7HSA",
    brand: "NGK",
    category: "spark-plugs",
    price: 140,
    description: "Standard spark plug for smooth starts and steady idle.",
    specs: [
      { label: "Model", value: "CR7HSA" },
      { label: "Pack", value: "1 pc" },
    ],
    compatibleWith: ["Activa", "Splendor", "Platina"],
    inStock: true,
  },
  {
    slug: "tvs-chain-sprocket-kit",
    name: "Chain & Sprocket Kit",
    brand: "TVS",
    category: "chains",
    price: 950,
    size: "Kit",
    description: "Chain with front and rear sprockets, sold as a matched kit.",
    specs: [
      { label: "Contents", value: "Chain + 2 sprockets" },
      { label: "Pack", value: "1 kit" },
    ],
    compatibleWith: ["Apache RTR", "Victor"],
    inStock: true,
  },
];
